# Generated by Django 3.1 on 2020-08-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperaturas_rf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='battery_low',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='channel',
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
