#!/bin/bash
/usr/bin/python3 /home/pi/django/temperaturas_rf/measuring.py &
/usr/local/bin/uwsgi --virtualenv /home/pi/django/djangoenv --socket /home/pi/django/django.socket --buffer-size=32768 --workers=5 --master --module controlcasa.wsgi_django --chmod-socket=666 --enable-threads &
/usr/local/bin/uwsgi --virtualenv /home/pi/django/djangoenv --http-socket /home/pi/django/web.socket --gevent 1000 --http-websockets --workers=2 --master --module controlcasa.wsgi_websocket --chmod-socket=666 --enable-threads &